"""Tests for the public distribution API."""

import mmmjax
import mmmjax.distributions as distributions

DISTRIBUTION_EXPORTS = [
    "bernoulli",
    "bernoulli_logcdf",
    "bernoulli_logit",
    "bernoulli_logit_logcdf",
    "bernoulli_logit_logpmf",
    "bernoulli_logit_logsf",
    "bernoulli_logit_rng",
    "bernoulli_logpmf",
    "bernoulli_logsf",
    "bernoulli_rng",
    "beta",
    "beta_logpdf",
    "beta_rng",
    "binomial",
    "binomial_logit",
    "binomial_logit_logpmf",
    "binomial_logit_rng",
    "binomial_logpmf",
    "binomial_rng",
    "categorical",
    "categorical_logit",
    "categorical_logit_logpmf",
    "categorical_logit_rng",
    "categorical_logpmf",
    "categorical_rng",
    "cauchy",
    "cauchy_logcdf",
    "cauchy_logpdf",
    "cauchy_logsf",
    "cauchy_rng",
    "dirichlet",
    "dirichlet_logpdf",
    "dirichlet_rng",
    "exponential",
    "exponential_logcdf",
    "exponential_logpdf",
    "exponential_logsf",
    "exponential_rng",
    "gamma",
    "gamma_logcdf",
    "gamma_logpdf",
    "gamma_logsf",
    "gamma_rng",
    "half_normal",
    "half_normal_logcdf",
    "half_normal_logpdf",
    "half_normal_logsf",
    "half_normal_rng",
    "inverse_gamma",
    "inverse_gamma_logcdf",
    "inverse_gamma_logpdf",
    "inverse_gamma_logsf",
    "inverse_gamma_rng",
    "laplace",
    "laplace_logcdf",
    "laplace_logpdf",
    "laplace_logsf",
    "laplace_rng",
    "lognormal",
    "lognormal_logcdf",
    "lognormal_logpdf",
    "lognormal_logsf",
    "lognormal_rng",
    "multinomial",
    "multinomial_logit",
    "multinomial_logit_logpmf",
    "multinomial_logit_rng",
    "multinomial_logpmf",
    "multinomial_rng",
    "negative_binomial",
    "negative_binomial_log",
    "negative_binomial_log_logpmf",
    "negative_binomial_log_rng",
    "negative_binomial_logpmf",
    "negative_binomial_rng",
    "normal",
    "normal_logcdf",
    "normal_logpdf",
    "normal_logsf",
    "normal_rng",
    "poisson",
    "poisson_log",
    "poisson_log_logcdf",
    "poisson_log_logpmf",
    "poisson_log_logsf",
    "poisson_log_rng",
    "poisson_logcdf",
    "poisson_logpmf",
    "poisson_logsf",
    "poisson_rng",
    "student_t",
    "student_t_logpdf",
    "student_t_rng",
    "truncated_normal",
    "truncated_normal_logcdf",
    "truncated_normal_logpdf",
    "truncated_normal_logsf",
    "truncated_normal_rng",
    "uniform",
    "uniform_logcdf",
    "uniform_logpdf",
    "uniform_logsf",
    "uniform_rng",
]


def test_distribution_exports_match_root_package() -> None:
    assert distributions.__all__ == DISTRIBUTION_EXPORTS
    assert set(DISTRIBUTION_EXPORTS).issubset(mmmjax.__all__)
    for name in DISTRIBUTION_EXPORTS:
        assert getattr(distributions, name) is getattr(mmmjax, name)
