"""Bayesian marketing mix modeling expressed entirely in JAX."""

from mmmjax.distributions import (
    beta,
    beta_logpdf,
    beta_rng,
    exponential,
    exponential_logpdf,
    exponential_rng,
    gamma,
    gamma_logpdf,
    gamma_rng,
    half_normal,
    half_normal_logpdf,
    half_normal_rng,
    lognormal,
    lognormal_logpdf,
    lognormal_rng,
    normal,
    normal_logpdf,
    normal_rng,
    student_t,
    student_t_logpdf,
    student_t_rng,
)
from mmmjax.model import Model
from mmmjax.parameters import Interval, LowerBound, Parameterization, Positive, Real, UpperBound

__version__ = "0.0.1"

__all__ = [
    "Interval",
    "LowerBound",
    "Model",
    "Parameterization",
    "Positive",
    "Real",
    "UpperBound",
    "beta",
    "beta_logpdf",
    "beta_rng",
    "exponential",
    "exponential_logpdf",
    "exponential_rng",
    "gamma",
    "gamma_logpdf",
    "gamma_rng",
    "half_normal",
    "half_normal_logpdf",
    "half_normal_rng",
    "lognormal",
    "lognormal_logpdf",
    "lognormal_rng",
    "normal",
    "normal_logpdf",
    "normal_rng",
    "student_t",
    "student_t_logpdf",
    "student_t_rng",
]
